### ISSUE TITLE
错判一些图片为非图片

### ISSUE THREAD

**Issue by realicing** [crazycodeboy/TakePhoto#10]
出现在魅族手机（型号为M463C），现在只发现所有的截屏图片都被认为不是图片，格式是jpg的

**Comment by crazycodeboy** [comment]
我这里没有此型号的测试机，如果你解决了这个问题可以通过pull requests，向TakePhoto贡献你的代码，谢谢

**Comment by anson39f** [comment]
怎么裁剪的600*600的图片呀，那个参数才是？

**Comment by crazycodeboy** [comment]
`public Builder setOutputX(int outputX) {
            options.setOutputX(outputX);
            return this;
        }

        public Builder setOutputY(int outputY) {
            options.setOutputY(outputY);
            return this;
        }`
@https://github.com/crazycodeboy/TakePhoto#cropoptions
@https://github.com/crazycodeboy/TakePhoto/blob/master/takephoto_library/src/main/java/com/jph/takephoto/model/CropOptions.java
