### ISSUE TITLE
您的轮子里混淆缺失-dontwarn rx.internal.util.unsafe.*

### ISSUE THREAD

**Issue by HPLY** [crazycodeboy/TakePhoto#102]
您的轮子里混淆缺失-dontwarn rx.internal.util.unsafe.*，是轮子里引用的multipleimageselect需要的，我这里打正式包发现老是失败，之前给你说过，现在解决了，希望作者您补充到混淆忽略里~

**Comment by crazycodeboy** [comment]
thanks.
