### ISSUE TITLE
裁剪可以固定裁剪比例吗

### ISSUE THREAD

**Issue by zmsoft** [crazycodeboy/TakePhoto#105]
裁剪可以固定裁剪比例吗？按照指定的比例进行裁剪

**Comment by crazycodeboy** [comment]
可以的，项目中有Demo可以参考一下

**Comment by zmsoft** [comment]
您好，使用系统相机拍照后跳转到第三方页面裁剪，会有一个裁剪框，那个框的大小能固定吗，按照16:9的比例
