### ISSUE TITLE
如果图片文件名字是非正常的，导致一处 java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gordonpro** [crazycodeboy/TakePhoto#107]
如果我的拍照 output 写成 `/mnt/sdcard/qoewiroqwer_912304123` 这样子。 没有 `.` 那么导致异常 

文件如下：

https://github.com/crazycodeboy/TakePhoto/blob/master/takephoto_library/src/main/java/com/jph/takephoto/uitl/TImageFiles.java#L138

```
public static String getMimeTypeByFileName(String fileName){
        return fileName.substring(fileName.lastIndexOf("."),fileName.length());
}

```

**Comment by gordonpro** [comment]
拍照并且裁剪时，会出现

**Comment by crazycodeboy** [comment]
要有个后缀的
