### ISSUE TITLE
选择图片返回后，弹出“选择默认打开的应用”的弹窗！

### ISSUE THREAD

**Issue by chenmingyin** [crazycodeboy/TakePhoto#109]
RT，每次选择完后都会弹窗这个弹窗，如果选择使用相册打开，那么在TakePhoto自带相册选择图片返回后会打开系统相册，不得不再次选择一遍。求解，怎么解决！

**Comment by crazycodeboy** [comment]
在系统弹出框中应该会有一个“使用用它打开”的复选框，选中该复选框就可以了。
