### ISSUE TITLE
请问，不申请相机权限为什么可以正常使用相机啊？相机也是个危险的权限啊

### ISSUE THREAD

**Issue by yannecer** [crazycodeboy/TakePhoto#11]

**Comment by crazycodeboy** [comment]
因为TakePhoto没有使用底层相机API，高版本的Android中会提示申请使用相机的提示。

**Comment by yannecer** [comment]
看了你的项目，我试了一下，不申请权限，用Intent打开相机，也是可以的，就是这句“startActivity(new Intent(MediaStore.ACTION_IMAGE_CAPTURE));”，新建一个项目，写这一句代码，不申请任何权限，可以正常打开相机，如果在manifest申请相机权限，在6.0以上以上系统中就需要代码再申请一次权限，不然会崩，但是在manifest和代码中都不申请权限反而能正常使用，感觉好纳闷

**Comment by crazycodeboy** [comment]
是的Android6.0新增了运行时权限(Runtime Permissions)，@http://blog.csdn.net/fengyuzhengfan/article/details/49253227

**Comment by yannecer** [comment]
不是的，我主要的疑惑是，可以不用再manifest中申请权限，也不用再在代码中申请权限，就是不用申请任何权限，依然可以使用正常相机，对这个纳闷

**Comment by crazycodeboy** [comment]
因为TakePhoto调用的是系统的照相机拍照，而没有去调用摄像头拍照所以不涉及到申请使用摄像头的权限

**Comment by yannecer** [comment]
大神没有明白我的意思，我是说，抛开TakePhoto，新建一个项目，用Intent打开手机的相机，不用申请任何权限，也能打开，这是为什么啊，就用这句代码“startActivity(newIntent(MediaStore.ACTION_IMAGE_CAPTURE));”

**Comment by crazycodeboy** [comment]
“startActivity(newIntent(MediaStore.ACTION_IMAGE_CAPTURE));”这句话是调用系统的相机程序，和你直接调用摄像头拍照是有区别的

**Comment by yannecer** [comment]
startActivity(newIntent(MediaStore.ACTION_IMAGE_CAPTURE));这句话应该是需要摄像头权限的，因为调用这句话时，在6.0系统上如果只在manifest中申请相机权限而不在程序中申请，程序是会崩的，说明在运行时，系统读取了manifest中的权限而没有发现代码中申请的权限，才导致了程序崩溃，如果这句话不需要权限，那manifest中申请不申请应该就和程序没有关系，程序也就不会崩了。问题有点多，大神见谅啊
