### ISSUE TITLE
图片压缩原理是什么

### ISSUE THREAD

**Issue by junyao-yu** [crazycodeboy/TakePhoto#14]
你这里的图片压缩是根据什么来压缩的呢？压缩的情况如何？比如，质量，大小。。。

**Comment by crazycodeboy** [comment]
[CompressConfig.java](https://github.com/crazycodeboy/TakePhoto/blob/master/takephoto_library/src/main/java/com/jph/takephoto/compress/CompressConfig.java)
这是TakePhoto用于图片压缩的配置类，你可以通过该类来配置对图片的压缩；另外，如果你有特殊需求可以修改[CompressImageUtil.java](https://github.com/crazycodeboy/TakePhoto/blob/master/takephoto_library/src/main/java/com/jph/takephoto/compress/CompressImageUtil.java)来实现。
