### ISSUE TITLE
通过组装的方式；在fragment里面不能使用

### ISSUE THREAD

**Issue by MoveToNext** [crazycodeboy/TakePhoto#15]
在执行takePhoto.onPickFromCaptureWithCrop(mSaveUri,cropOptions);操作后不能在onActivityResult执行裁剪的页面

**Comment by crazycodeboy** [comment]
需要重写Fragment的onActivityResult方法，eg:@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        getTakePhoto().onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }
可参考：[TakePhotoFragment.java)](https://github.com/crazycodeboy/TakePhoto/blob/master/takephoto_library/src/main/java/com/jph/takephoto/app/TakePhotoFragment.java)
