### ISSUE TITLE
三星选择照片旋转问题

### ISSUE THREAD

**Issue by weikeshidai** [crazycodeboy/TakePhoto#150]
三星拍照设置setCorrectImage方法可以解决拍照照片被旋转的问题，但是选择照片完后依旧是一张被旋转的照片，除非设置裁剪参数裁完后照片才不会旋转。

请问下这个问题怎么解决？

**Comment by crazycodeboy** [comment]
开启选择纠正：[旋转纠正](https://github.com/crazycodeboy/TakePhoto/blob/master/takephoto_library/src/main/java/com/jph/takephoto/model/TakePhotoOptions.java#L21)

**Comment by gupengcheng** [comment]
开启了旋转纠正还是不起作用？

**Comment by szitguy** [comment]
三星手机，我就用系统的裁切🤕
builder.setWithOwnCrop(!"samsung".equals(Build.BRAND));
