### ISSUE TITLE
朋友这个toolbar颜色不对的呀

### ISSUE THREAD

**Issue by yishangfei** [crazycodeboy/TakePhoto#167]
![image](https://cloud.githubusercontent.com/assets/15099278/23788155/44856dd4-05b0-11e7-9400-113e5f38bf8d.png)
![image](https://cloud.githubusercontent.com/assets/15099278/23788157/4807207e-05b0-11e7-9e73-d1b797dc8296.png)

求解决呀

**Comment by yishangfei** [comment]
![image](https://cloud.githubusercontent.com/assets/15099278/23790339/a585e84e-05b9-11e7-999c-7c6a11e0d157.png)
上面那个写了  下面就写了没用只能选择一张       不写上面那个只能跳转系统相册点击才进入TakePhoto的相册    两个问题

**Comment by Rabbit95** [comment]
请问toolbar颜色问题解决了吗？
