### ISSUE TITLE
为什么我跟你demo的一样做的，但是走不到takeSuccess方法啊？

### ISSUE THREAD

**Issue by hong940619** [crazycodeboy/TakePhoto#17]
if (ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)
                != PackageManager.PERMISSION_GRANTED) {
            //申请WRITE_EXTERNAL_STORAGE权限
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},
                    1);
        }
        File file=new File(Environment.getExternalStorageDirectory(), "/temp/"+System.currentTimeMillis() + ".jpg");
        if (!file.getParentFile().exists())file.getParentFile().mkdirs();
        Uri imageUri = Uri.fromFile(file);
        CompressConfig compressConfig=new CompressConfig.Builder().setMaxSize(50*1024).setMaxPixel(800).create();
        //CropOptions cropOptions=new CropOptions.Builder().setAspectX(1).setAspectY(1).setWithOwnCrop(withOwnCrop).create();
        getTakePhoto().onEnableCompress(compressConfig,true).onPickFromCapture(imageUri);

**Comment by Sss1986** [comment]
我也是这样。。 一直是操作被取消

**Comment by crazycodeboy** [comment]
请使用最新版
