### ISSUE TITLE
第一次从相册中选择图片时getCompressPath()得到的值是正常的,但是第二次开始getCompressPath()就是null

### ISSUE THREAD

**Issue by hjmJhon** [crazycodeboy/TakePhoto#170]
不管是设置从文件中选择还是从相册中选择,如题的现象一直存在

**Comment by wangyuan0217** [comment]
我也是一样的，连续单次选择图片，设置了压缩的前提下，只有第一次压缩了，第二次以后都没有压缩。

**Comment by wangyuan0217** [comment]
这个issue为毛就close了

**Comment by wyj365372704** [comment]
他这个确实有这个问题,但是你可以规避:
每次调用TakePhoto.onPickXXX( )之前,你都对TakePhoto对象重新配置CompressConfig, takePhoto.onEnableCompress(config, true);
注意TakePhoto对象不能做新的实例化.

比如我这里getTakePhoto( )这么写的:
private TakePhoto getTakePhoto() {
        if (takePhoto == null) {
            takePhoto = (TakePhoto) TakePhotoInvocationHandler.of(this).bind(new TakePhotoImpl(this, this));
        }
        CompressConfig config = new CompressConfig.Builder()
                .setMaxSize(60 * 1024)
                .setMaxPixel(800)
                .enableReserveRaw(false)
                .create();
        takePhoto.onEnableCompress(config, true);
        return takePhoto;
    }

选照片前都调用一次getTakePhoto( ) 即可:
 getTakePhoto();
        takePhoto.onPickFromDocumentsWithCrop(imageUri, cropOptions);

或者

 getTakePhoto();
        takePhoto.onPickFromCaptureWithCrop(imageUri, cropOptions);

**Comment by wangyuan0217** [comment]
好鸡肋，同样鸡肋的是 我之前是判断选的图 > 1M  自己在走一遍luban，
