### ISSUE TITLE
demo的这一句是不是写错了

### ISSUE THREAD

**Issue by fan31415** [crazycodeboy/TakePhoto#25]
在TakePhoto/simple/src/main/java/com/jph/simple/CustomHelper.java里的configCompress方法中的这一句CompressConfig config= new CompressConfig.Builder().setMaxPixel(maxSize).setMaxPixel(maxPixel).create();
好像，Builder()后应该改为setMaxSize(maxSize)

**Comment by crazycodeboy** [comment]
是的，希望不会对大家造成误解，谢谢指正。
