### ISSUE TITLE
与融云IMKit的FileProvider冲突

### ISSUE THREAD

**Issue by wangyuan0217** [crazycodeboy/TakePhoto#251]

**Comment by xujianlafeng** [comment]
兄弟，我也遇到这个问题了，咋解决的！！

**Comment by gasry1989** [comment]
在APP中引用IMKit的FileProvider直接注释掉
然后在takephoto的xml/file_paths.xml改成如下
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <paths>
        <root-path path="" name="camera_photos" />
        <external-path name="rc_external_path" path="."/>
    </paths>
</resources>

就可以了

**Comment by gasry1989** [comment]
root-path path="" name="camera_photos" 
external-path name="rc_external_path" path="."

**Comment by wangyuan0217** [comment]
thanks

**Comment by raighneweng** [comment]
我的解决方案：
新建一个RongFileProvider
```
public class RongFileProvider extends android.support.v4.content.FileProvider {
}
```
然后在App内manifest内
```
<provider
            android:name=".util.RongFileProvider"
            android:authorities="package包名.FileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="name,authorities,exported,grantUriPermissions">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_path"
                tools:replace="name,resource"/>
        </provider>
```

**Comment by wangyuan0217** [comment]
me too   我的项目中有bugly RongIM 而且也用了这个takephoto  这三个里面都有FileProvider   我的解决方法就是把bugly 和RongIM 分别在manifest中重新指向自定的的FileProvider  做法如楼上所述

**Comment by to686312** [comment]
你们有没有详细的解决方案  求告知
