### ISSUE TITLE
拍照裁剪时对内存的使用率过高

### ISSUE THREAD

**Issue by EasonHolmes** [crazycodeboy/TakePhoto#26]
拍照裁剪时对内存的使用率过高

**Comment by crazycodeboy** [comment]
请问，你是用的那种裁切照片的方式？

**Comment by crazycodeboy** [comment]
裁切照片需要将照片加载到内存中处理，无论是第三方裁切工具还是TakePhoto自带的都是避免不了的需要使用一定的内存，这个根据照片的分辨率大小不同而不同。
另外，TakePhoto支持使用第三方裁切工具进行裁切（如系统相册的裁切工具），第三方裁切工具虽然也占内存，但不会消耗系统分配给你应用的内存。
