### ISSUE TITLE
三星拍照后照片还是被旋转了

### ISSUE THREAD

**Issue by moonljt521** [crazycodeboy/TakePhoto#28]
三星拍照后照片还是被旋转了

**Comment by crazycodeboy** [comment]
TakePhoto对拍照后被旋转的照片是有做纠正处理的，这个在三星 GALAXY S4，Note 5 ，S6 Edge+等测试过，都是正常的，不知楼主使用的TakePhoto是不是最新版？

**Comment by moonljt521** [comment]
@crazycodeboy  takephoto 是最新版，在note2上测试的

**Comment by crazycodeboy** [comment]
三星 Note 2是四年前的手机了，实在没找到，不过刚才在三星 Note 3上测了一下，发现三星 Note 3在拍照时屏幕会强制横屏，拍的照片自然也是横屏的，旋转角度为0。

**Comment by mhhwheat** [comment]
那么请问应该怎么处理

**Comment by crazycodeboy** [comment]
@mhhwheat 看这里[获取更高的兼容性](https://github.com/crazycodeboy/TakePhoto#获取更高的兼容性)

**Comment by mhhwheat** [comment]
@crazycodeboy  我把调用到takePhoto的页面全都配置了下面连个属性，依然还是不行
`android:screenOrientation="portrait"`
` android:configChanges="orientation|keyboardHidden|screenSize"`

**Comment by lxykad** [comment]
三星s6 拍照不旋转，从相册获取照片旋转
