### ISSUE TITLE
拍照后调用裁剪崩溃频率很高

### ISSUE THREAD

**Issue by moonljt521** [crazycodeboy/TakePhoto#29]
拍照后调用裁剪崩溃频率很高，大概是占内存过多

**Comment by Lyon1994** [comment]
@moonljt521 
![image](https://cloud.githubusercontent.com/assets/8456652/19211137/eb5c7fb0-8d67-11e6-9567-7b8b04cd2edf.png)
建议申请大内存，应该是相机默认分辨率是2k级别的，拍出来的照片占内存太大，我之前就踩过这个坑

**Comment by moonljt521** [comment]
@Lyon1994  不应该以申请内存的方式来解决这个问题啊，要是自己手写就是减小分辨率；
另外根本没有适配最典型的三星手机拍照旋转问题，不明白为什么有这么多star ，都是托么~

**Comment by crazycodeboy** [comment]
@moonljt521 
1.部分手机拍照时会把Activity回收，这点TakePhoto是有做恢复处理的，不知你是否有按照使用说明做呢？如果[simple](https://github.com/crazycodeboy/TakePhoto/tree/master/simple)能正常运行，那么可能是你集成的问题，可以参照simple去使用，另外如果对Readme上的使用说明有疑问可以提issue出来。
2.裁切照片需要将照片加载到内存中处理，无论是第三方裁切工具还是TakePhoto自带的都是避免不了的需要使用一定的内存，这个根据照片的分辨率大小不同而不同，但不会造成崩溃的。

**Comment by moonljt521** [comment]
@crazycodeboy  我直接使用的demo来拍照，拍照后照片在三星上是旋转的
