### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by anson39f** [crazycodeboy/TakePhoto#3]
用酷派4.1系统，使用相册裁剪和拍照裁剪都保存不了图片，其中拍照进不到裁剪界面。相册选择裁剪之后保存后，没有发现文件，界面显示不出图片。

**Comment by crazycodeboy** [comment]
1.是酷派手机那个型号的？
2.用的是酷派官方系统还是刷的第三方的系统呢？
你可以试一下安装快图浏览然后再拍照裁切试一下

**Comment by anson39f** [comment]
1,酷派5890 4.12系统
2,应该是官方，测试机，来是时候就有了。
3，安装了，拍照一样不行，相册用快图截图后保存，一直转圈。。。

**Comment by crazycodeboy** [comment]
只拍照片不裁切这个功能是否正常呢？
这一步做了吗？
[关于兼容性问题](https://github.com/crazycodeboy/TakePhoto#关于兼容性问题)  
如果还是不行，请调试一下把异常log发过来，以便查找问题

**Comment by crazycodeboy** [comment]
此问题已解决，详见[TakePhoto V2.0.0](https://github.com/crazycodeboy/TakePhoto/)
