### ISSUE TITLE
请求码的设置

### ISSUE THREAD

**Issue by chenjiaawei1015** [crazycodeboy/TakePhoto#31]
通过TakePhoto自带的裁切工具裁切图片时
TUtils类中的cropWithOwnApp方法,
3.0版本中没有设置requestCode,导致在onActivityResult方法中获取的requestCode无法确定,
建议方法参数中添加requestCode参数或者设置为TConstant.RC_CROP

**Comment by crazycodeboy** [comment]
自带裁切工具裁切requestCode为Crop.REQUEST_CROP，这个在TakePhotoImpl中是有处理的，
```
 case TConstant.RC_CROP://裁剪照片返回结果
 case Crop.REQUEST_CROP://裁剪照片返回结果  
                if (resultCode == Activity.RESULT_OK) {
                    if (multipleCrop != null) {
...```
