### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by caixiaoxu** [crazycodeboy/TakePhoto#32]
安装demo后，再安装集成TakePhoto的项目，会出现INSTALL_FAILED_CONFLICTING_PROVIDER，应该是这个的问题：
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.jph.takephoto.fileprovider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
但这个配置是写在框架中的，对于这种类似问题应该怎么解决，求指教

**Comment by crazycodeboy** [comment]
对的，provider域名冲突，在Android系统中不允许有两个同名的provider，你可以把simple卸载，然后在装集成的应用。后期会优化一下，让使用TakePhoto的多个应用可以同时存在。
