### ISSUE TITLE
升级glide4之后崩溃

### ISSUE THREAD

**Issue by yuanmenghao** [crazycodeboy/TakePhoto#335]
NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest
  升级glide4之后不兼容，怎么办，有解决方案没

**Comment by Bessie330** [comment]
我也遇到这个问题了，直接报错，相册功能无法使用

**Comment by loperSeven** [comment]
1.将TakePhoto  Demo下载，以module方式导入项目更改glide版本为 4.0及以上并重新实现glide图片加载
2.将项目中其他glide4版本降到3.6版本
