### ISSUE TITLE
会和Rxjava2冲突

### ISSUE THREAD

**Issue by ForLovelj** [crazycodeboy/TakePhoto#336]
搞不懂为什么会和Rxjava2冲突，看错误是因为引用了Rxjava1引起错误的。
com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/rxjava.properties
File1: C:\Users\Administrator.gradle\caches\modules-2\files-2.1\io.reactivex\rxjava\1.2.1\4e4cfa4adc74521d5966799fa5ab70b733552f68\rxjava-1.2.1.jar
File2: C:\Users\Administrator.gradle\caches\modules-2\files-2.1\io.reactivex.rxjava2\rxjava\2.1.3\c6a633c63607f09f77f424b5c52522a7607cedae\rxjava-2.1.3.jar

虽然通过
packagingOptions {
exclude 'META-INF/rxjava.properties'
}
排除了这个文件编译不报错了，但是很奇怪。光依赖TakePhoto不报错，但一使用TakePhoto实例就报错。

**Comment by Xiasm** [comment]
我也遇到这个问题了，我感觉应该是rxJava1和rxJava2不能共存

**Comment by wgheng** [comment]
这个库依赖advancedluban 1.3.2鲁班压缩库是Rxjava1.x，把advancedluban更新到最新版本就好了
