### ISSUE TITLE
Dead problem

### ISSUE THREAD

**Issue by MakeCodeFly** [crazycodeboy/TakePhoto#339]
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/-2/base.apk:classes37.dex)

**Comment by bbbBBBSG** [comment]
大哥，我也遇到了这个bug，怎么解决啊

**Comment by MakeCodeFly** [comment]
现在应该没有这个问题了吧？你直接导入源码  修改glide版本即可
