### ISSUE TITLE
关于provider相同无法安装的问题解决

### ISSUE THREAD

**Issue by zhangloveyan** [crazycodeboy/TakePhoto#34]
描述：手机上已有一个app使用本库的依赖，当你app在用这个库的依赖时，由于使用了provider，会检测到INSTALL FAILED CONFLICTING PROVIDER 问题，安装失败。
解决方法：将本库下载到本地，导入作为项目依赖，修改2个地方
1、AndroidManifest中的android:authorities="xx"的值（xx为你改后的值）。
2、常量类TConstant中的public final static String FILE_PROVIDER="xx"的值（与1中的值保持一致）。
重新编译，就ok了。
望作者采纳。

**Comment by crazycodeboy** [comment]
谢谢，最新版本以解决这个问题 #32
