### ISSUE TITLE
请把图片加载（Glide）解耦分离出来吧。

### ISSUE THREAD

**Issue by 7xyu** [crazycodeboy/TakePhoto#342]
我这里的glide提升到4，这框架就用不了 了。框架的Glide.with.load.placeholder报错，因为现在glide4之后，都设置闲置图片等放到了RequestOptions里。
重点是还是把图片加载的选择交给用户把，把自身的glide分离出来吧

**Comment by guohui910076299** [comment]
嗯嗯，我也觉得分离出来比较好

**Comment by 7xyu** [comment]
最后把项目拷贝下来了，发现是引用的multiimageselector库再引用的3.6.0的glide。索性又把该库也down下来。现在改成4.0以上的glide了。
