### ISSUE TITLE
多选模式，多次选择问题

### ISSUE THREAD

**Issue by Demarcia-cn** [crazycodeboy/TakePhoto#35]
我设置选择模式为多选，动态设置选择数量：limitNum=maxNum-selectedNum，当limitNum=1时，会自动变为单选择模式，选择完成后，仍可以继续选择，选择模式为多选，限制张数为1.
机型LG-Nexus5

**Comment by Demarcia-cn** [comment]
比如设置最大张数为6，选择5张之后返回，再选就自动跳到了单选模式，选择完成后，还可以选择，模式变为多选，限制张数为1

**Comment by Demarcia-cn** [comment]
问题解决了，自己做了选择数量判断。

**Comment by crazycodeboy** [comment]
配置，一次有效。第二次会清楚第一次的配置

**Comment by Demarcia-cn** [comment]
看来是我多此一举了，哈哈，多谢~
