### ISSUE TITLE
关于调用相机出现UndeclaredThrowableException的bug解决

### ISSUE THREAD

**Issue by liudf731098327** [crazycodeboy/TakePhoto#359]
其实这里是7.0配置了FileProvider和TakePhoto框架冲突造成的，说下我的解决方法吧，通过查看TakePhoto发现，需要在xml文件夹中配置file_paths.xml（跟TakePhoto的resources同名），添加<external-path
        name="demo"
        path="images/"/>即可

**Comment by liudf731098327** [comment]
添加<external-path
        name="demo"
        path="images/"/>即可

**Comment by liudf731098327** [comment]
添加<external-path
        name="demo"
        path="images/"/>即可

**Comment by taiji1** [comment]
> 其实这里是7.0配置了FileProvider和TakePhoto框架冲突造成的，说下我的解决方法吧，通过查看TakePhoto发现，需要在xml文件夹中配置file_paths.xml（跟TakePhoto的resources同名），添加即可
你说的解决不了问题，第三方的图片文件照样crash
将takePhoto.onPickFromDocumentsWithCrop(imageUri, getCropOptions());
替换成takePhoto.onPickFromGalleryWithCrop(imageUri, getCropOptions());
用系统的裁剪才行，真正报错的原因是读取文件解析空指针了
