### ISSUE TITLE
不兼容Glide 4.0 版本及以上，出现崩溃

### ISSUE THREAD

**Issue by loperSeven** [crazycodeboy/TakePhoto#366]
崩溃内容：java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager

崩溃位置：com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter

即时已module方式导入TakePhoto也无法自行更改错误，还希望作者能及时处理一下

**Comment by Destiny01** [comment]
我的也是一样的问题
