### ISSUE TITLE
onPickMultiple 方法报错（HTC M9pw）

### ISSUE THREAD

**Issue by chengkaizone** [crazycodeboy/TakePhoto#370]
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.tony.systemui-2/base.apk)
                                                                       at com.darsh.multipleimageselect.adapters.CustomAlbumSelectAdapter.getView(CustomAlbumSelectAdapter.java:45)

**Comment by wangjunmei** [comment]
我也遇到了同样的问题

**Comment by hailongfeng** [comment]
我也遇到了同样的问题，解决了吗？

**Comment by sidonglee** [comment]
我也遇到了同样的问题。。
