### ISSUE TITLE
外部内存卡中图片获取失败。还希望加下。

### ISSUE THREAD

**Issue by z2045217** [crazycodeboy/TakePhoto#38]
在takefail失败中信息是： 图片压缩失败:质量压缩失败 picturePath:/storage/sdcard1/tencent/micromsg/weixin/microMsg.1461378756244.jpg。。

**Comment by crazycodeboy** [comment]
从路径上看，你选择的应该是微信聊天记录中的图片，选择其他路径试一下看能否成功。

**Comment by z2045217** [comment]
恩。内部存储卡的没有问题。但是只要是外置的sdk卡就会出现问题。。

**Comment by crazycodeboy** [comment]
从外置SD卡的其他位置选个图片试一下

**Comment by z2045217** [comment]
好的。试试。

**Comment by z2045217** [comment]
这个是sdk卡中的相册图片。图片压缩失败:质量压缩失败 picturePath:/storage/sdcard1/DCIM/Camera/IMG_20160417_171842.jpg

**Comment by crazycodeboy** [comment]
在v3.0.2中已支持，` compile 'com.jph.takephoto:takephoto_library:3.0.2'`
