### ISSUE TITLE
纠正照片的旋转角度引起崩溃

### ISSUE THREAD

**Issue by JakeWang123** [crazycodeboy/TakePhoto#40]
/**
     * 纠正照片的旋转角度
     * @param path
     */
    public void correctImage(Uri path){

        String imagePath=TUriParse.parseOwnUri(path);
        int degree;
        if((degree=getBitmapDegree(imagePath))!=0){
            Bitmap bitmap= BitmapFactory.decodeFile(imagePath);
            if(bitmap==null)return;
            Bitmap resultBitmap=rotateBitmapByDegree(bitmap,degree);
            if(resultBitmap==null)return;
            try {
                resultBitmap.compress(Bitmap.CompressFormat.JPEG,100,new FileOutputStream(new File(imagePath)));
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }
    }

这段代码会在三星中使得内存陡增，建议加个纠正开关或者根据设置的compress先压缩再旋转

**Comment by crazycodeboy** [comment]
谢谢反馈，后期会优化
