### ISSUE TITLE
魅族 flyme bug

### ISSUE THREAD

**Issue by jin123d** [crazycodeboy/TakePhoto#41]
flyme中选择单张图片，如果选择截图，提示选择不是图片。
takeFail:选择的文件不是图片 图片压缩失败:/storage/emulated/0/temp/1476416342055.jpg is compress failures picturePath:/storage/emulated/0/temp/1476416342055.jpg

**Comment by woniu0936** [comment]
我也遇到了相同的问题：以下是log
`I/com.jph.takephoto.app.TakePhotoActivity: takeFail:选择的文件不是图片 图片压缩失败:/storage/emulated/0/say_1477390142966.jpeg is compress failures picturePath:/storage/emulated/0/say_1477390142966.jpeg
10-25 18:09:20.584 25997-25997/com.gouhuoapp.say D/UserModifyActivity: path: /storage/emulated/0/say_1477390142966.jpeg, msg:选择的文件不是图片 图片压缩失败:/storage/emulated/0/say_1477390142966.jpeg is compress failures picturePath:/storage/emulated/0/say_1477390142966.jpeg
10-25 18:09:20.584 25997-25997/com.gouhuoapp.say W/System.err: com.jph.takephoto.model.TException: 选择的文件不是图片
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.onCrop(TakePhotoImpl.java:269)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at com.jph.takephoto.app.TakePhotoImpl.onActivityResult(TakePhotoImpl.java:110)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at com.jph.takephoto.permission.TakePhotoInvocationHandler.invoke(TakePhotoInvocationHandler.java:39)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:397)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at $Proxy5.onActivityResult(Unknown Source)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at com.gouhuoapp.say.view.activity.TakePhotoActivity.onActivityResult(TakePhotoActivity.java:45)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at com.gouhuoapp.say.view.activity.UserModifyActivity.onActivityResult(UserModifyActivity.java:414)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6378)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3970)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4017)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:178)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.os.Looper.loop(Looper.java:192)
10-25 18:09:20.585 25997-25997/com.gouhuoapp.say W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5784)`

**Comment by woniu0936** [comment]
我测试的手机是魅蓝3，系统是阿里云os 3.1.6，相册里面拍的照片没问题，但是截图会报如上错误

**Comment by crazycodeboy** [comment]
@woniu0936 能说一下具体流程吗

**Comment by woniu0936** [comment]
@crazycodeboy 如下是我使用的方式
configCompress(takePhoto);
takePhoto.onPickFromGallery();
`/**
     * 压缩
     *
     * @param takePhoto
     */
    private void configCompress(TakePhoto takePhoto) {
        int maxSize = 1200;
        int maxPixel = 512 * 1024;  //512kb
        CompressConfig config = new CompressConfig.Builder()
                .setMaxPixel(maxSize)
                .setMaxPixel(maxPixel)
                .create();
        takePhoto.onEnableCompress(config, false);
    }`
这是我使用的代码，然后手机相册里面的照片分为两部分，一部分是手机拍的，使用没有问题，一部是截图，使用的时候就会报错：   takeFail:选择的文件不是图片 图片压缩失败:/storage/emulated/0/say_1477390142966.jpeg is compress failures picturePath:/storage/emulated/0/say_1477390142966.jpeg

**Comment by woniu0936** [comment]
@crazycodeboy 我写了个demo，复现了一下这个bug，发到你的邮箱(crazycodeboy@gmail.com)了，请看看，谢谢

**Comment by crazycodeboy** [comment]
@woniu0936 
```
.setMaxPixel(maxSize)
.setMaxPixel(maxPixel)
```
你的意识是：
```
.setMaxPixel(maxPixel)
.setMaxSize(maxSize)
```
吗？
