### ISSUE TITLE
三星s4拍照崩溃

### ISSUE THREAD

**Issue by renyuan1991** [crazycodeboy/TakePhoto#45]
选择拍照后在点击保存的时候程序崩溃，错误信息是在OnActivityForResult中我们的takephoto对象为null

**Comment by crazycodeboy** [comment]
下载simple试一下，[simple](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)

**Comment by renyuan1991** [comment]
simple不会崩溃
    public TakePhoto getTakePhoto(){
        if (takePhoto==null){
            takePhoto = new TakePhotoImpl(this,this);
        }
        return takePhoto;
    }
报的错误是这个方法返回的对象为空....

**Comment by renyuan1991** [comment]
getTakePhoto().onActivityResult(requestCode, resultCode, data);
resultCode = -1;
data = null;

**Comment by renyuan1991** [comment]
抱歉，没有仔细阅读你的文档，谢谢你！
