### ISSUE TITLE
华为 荣耀4x 系统6.0.1

### ISSUE THREAD

**Issue by blackbai11** [crazycodeboy/TakePhoto#46]
拍照和相册选择 都 找不到文件

**Comment by crazycodeboy** [comment]
下载simple试一下，[simple](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)

**Comment by blackbai11** [comment]
是我的问题，6.0的权限问题。是这样的，我用的小米，默认不需要写sd卡的权限。导致我没有加。而引用的是老版本的，没有自动判断权限。打扰了

**Comment by crazycodeboy** [comment]
解决问题就好
