### ISSUE TITLE
在关闭裁剪的情况下，直接拍照返回图片路径不正确.

### ISSUE THREAD

**Issue by CaesarZhao** [crazycodeboy/TakePhoto#47]
![bug1](https://cloud.githubusercontent.com/assets/4359893/19545223/2dd5e1ee-96b7-11e6-843c-ad2a8f229d6e.png)

设备nexus 5 
版本 6.0

不知道算不算bug  : )

**Comment by crazycodeboy** [comment]
以 void takeSuccess(TResult result);返回结果为准
