### ISSUE TITLE
AlbumSelectActivity中Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);转型报错

### ISSUE THREAD

**Issue by parcool** [crazycodeboy/TakePhoto#48]
如题。在activity_album_select.xml里的include->toolbar.xml中，debug模式下看到include被转为了FrameLayout而不是ToolBar，所以转型出错崩溃了。
android studio2.2
compileSdkVersion 24
buildToolsVersion "24.0.2"
minSdkVersion 14
targetSdkVersion 24
compile 'com.android.support:support-v4:24.2.0'

**Comment by parcool** [comment]
当然，在activity_image_select.xml中同样的问题。

**Comment by crazycodeboy** [comment]
下载simple试一下，[simple](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)

**Comment by parcool** [comment]
@crazycodeboy simple没有问题，试过了。集成到项目中由于使用的版本跟你这个simple不同，所以会出错。`    
        
        
        
        
    <android.support.v7.widget.Toolbar
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:theme="@style/CustomToolbarTheme" />`做如上改动后能正常运行。另外：simple与sample楼主想表达的单词是不是错了啊

**Comment by crazycodeboy** [comment]
建议使用最新版，simple与sample是拼写错误，有时间会改过来，谢谢提醒

**Comment by llfnqt** [comment]
现在的2020年了还没改过来啊
