### ISSUE TITLE
Could not find support-v4.jar

### ISSUE THREAD

**Issue by tianyajuechen** [crazycodeboy/TakePhoto#50]
Error:A problem occurred configuring project ':takephoto_library'.
> Could not find support-v4.jar (com.android.support:support-v4:24.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-v4/24.0.0/support-v4-24.0.0.jar

我引用的是compile 'com.jph.takephoto:takephoto_library:3.0.3'这个版本，发现找不到v4-24.0.0版本的jar。
后来只能引入takephoto_library更改了v4.jar版本，建议你重新更新下你的aar

**Comment by crazycodeboy** [comment]
Android Support Repository 为33，对应的support-v4为com.android.support:support-v4:24.0.0
