### ISSUE TITLE
继承TakePhotoActivity ，在takeSuccess中返回的List，images.get(0).getPath()出来会出现/storage/emulated/0/storage/emulated/0/temp/1477450448460.jpg

### ISSUE THREAD

**Issue by pbaiyy** [crazycodeboy/TakePhoto#51]
路径的前面一段会重复，为什么？

**Comment by crazycodeboy** [comment]
运行simple看一下，另外可以下载simple试一下，[simple](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)

**Comment by b4nst0n** [comment]
sample同样的问题，使用拍照的话，6.0以上会出现这个问题，重复拿了 /storage/emulated/0/ 这一段路径，4+的正常。

**Comment by crazycodeboy** [comment]
方便提供一下手机型号和手机系统版本吗？

**Comment by b4nst0n** [comment]
一：小米5，系统版本6.0.1
二：三星C5，系统版本6.0.1

**Comment by b4nst0n** [comment]
TUriParse.java文件的parseOwnUri方法，第76行

**Comment by pbaiyy** [comment]
我这边是 小米5     6.0.1  sample不选择裁切时有问题。。。
               三星S7 edge 6.0.1   同上
