### ISSUE TITLE
依赖添加不了.

### ISSUE THREAD

**Issue by HyggeBo7** [crazycodeboy/TakePhoto#513]
![image](https://user-images.githubusercontent.com/29586966/59175386-f2b05900-8b87-11e9-989e-77c8f240fefc.png)

**Comment by 616852636** [comment]
implementation 'org.devio.takephoto:takephoto_library:4.1.0' 这个是正确的地址，作者改包名了

**Comment by HyggeBo7** [comment]
> 实施'org.devio.takephoto：takephoto_library：4.1.0'这个是正确的地址，作者改包名了

好的，感谢.
