### ISSUE TITLE
两个项目同时使用，好像安装出问题

### ISSUE THREAD

**Issue by HulShun** [crazycodeboy/TakePhoto#53]
1.如果两个项目同时使用的话，两个项目同时安装在手机上会出现INSTALL_FAILED_CONFLICTING_PROVIDER 错误。请问库中是不是使用了provider？ android上不允许有两个重名的provider的意思。
2.同时压缩三张图片以上，会提示压缩失败。

**Comment by crazycodeboy** [comment]
请使用最新版
