### ISSUE TITLE
压缩和裁剪的都是原图

### ISSUE THREAD

**Issue by loganguo** [crazycodeboy/TakePhoto#55]
感谢大神贡献如此强大好用的库。
但是在用的时候发现压缩和裁剪的都是原图，能否保留原图，比如像Photoshop那样操作拷贝的图片呢？

**Comment by qinyang1018** [comment]
是的  我也发现这个问题了 刚要提issues，就看见你的了，相册的原图直接被压缩，这样体验不是很好

**Comment by crazycodeboy** [comment]
好的，后期会添加支持

**Comment by loganguo** [comment]
我们的产品是要求拍照的照片放在SD卡上的app相关文件夹中，允许编辑原图。从相册中选择照片时，由于时公共区域，只允许拷贝原图进行编辑。

**Comment by qinyang1018** [comment]
现在裁剪不是操作的原图 ，  压缩是的 ，你也可以先自行修改给压缩传一个outUri的参数，压缩完成后写入到outUri的路径上
