### ISSUE TITLE
华为mate8 从相册获取图片没走回调

### ISSUE THREAD

**Issue by qinyang1018** [crazycodeboy/TakePhoto#56]
华为mate8 从相册获取图片，启动压缩，没走回调，demo测试也是这样

**Comment by qinyang1018** [comment]
![image](https://cloud.githubusercontent.com/assets/15726024/19923469/80507090-a122-11e6-81dd-4733c24469c8.png)
启动裁剪在压缩就没问题，是不是因为图片过大？

**Comment by qinyang1018** [comment]
不启用压缩也没问题

**Comment by qinyang1018** [comment]
从错误看是压缩完写入失败了，但是裁剪的写入为什么能成功呢

**Comment by qinyang1018** [comment]
我debug看了下 你裁剪是吧结果写到另一个目录下了，压缩是覆盖了原图    
<img width="608" alt="qq20161102-0 2x" src="https://cloud.githubusercontent.com/assets/15726024/19924396/ada7eda8-a126-11e6-85a9-04513d2023c7.png">

原图是这个路径写入失败没权限

**Comment by qinyang1018** [comment]
裁剪是传入了一个outUri压缩能否也如此  这样也不会覆盖原图

**Comment by crazycodeboy** [comment]
从Log上看应该是写入权限的问题，后期会添加压缩后图片的输出Uri选项

**Comment by qinyang1018** [comment]
貌似这些图片在系统目录  读出来没问题  但是原路径写入回去就没权限了

**Comment by namezhouyu** [comment]
@crazycodeboy 问下作者，release 4.0 图片压缩后不会覆盖原图吧？（luban）

**Comment by qinyang1018** [comment]
@namezhouyu 不会了
