### ISSUE TITLE
tips提示信息是否可以自定义

### ISSUE THREAD

**Issue by yangxiaoge** [crazycodeboy/TakePhoto#58]
![image](http://ww2.sinaimg.cn/mw1024/c05ae6b6gw1f9fyrfhlbuj20ta09madg.jpg)

**Comment by yangxiaoge** [comment]
<string name="tip_compress">Being compressed...</string>
    <string name="tip_compress_failed">"%1$s Picture compression failure:%2$s picturePath:%3$s"</string>
    <string name="tip_no_camera">No camera</string>
    <string name="tip_permission_camera">No permission to use the camera, open the rights management</string>
    <string name="tip_permission_camera_storage">No permission to use the camera and SD card, open the rights management</string>
    <string name="tip_permission_storage">No permission to use the SD card, open the rights management</string>
    <string name="tip_tips">Tips</string>
    <string name="tip_type_not_image">Choose not pictures</string>

**Comment by yangxiaoge** [comment]
<string name="tip_compress">Being compressed...</string>
    <string name="tip_compress_failed">"%1$s Picture compression failure:%2$s picturePath:%3$s"</string>
    <string name="tip_no_camera">No camera</string>
    <string name="tip_permission_camera">No permission to use the camera, open the rights management</string>
    <string name="tip_permission_camera_storage">No permission to use the camera and SD card, open the rights management</string>
    <string name="tip_permission_storage">No permission to use the SD card, open the rights management</string>
    <string name="tip_tips">Tips</string>
    <string name="tip_type_not_image">Choose not pictures</string>

**Comment by crazycodeboy** [comment]
可以的，在你项目的values/strings.xml中添加你需要修改的提示信息即可：
```
<string name="tip_compress">Being compressed...</string>
<string name="tip_compress_failed">"%1$s Picture compression failure:%2$s picturePath:%3$s"</string>
<string name="tip_no_camera">No camera</string>
<string name="tip_permission_camera">No permission to use the camera, open the rights management</string>
<string name="tip_permission_camera_storage">No permission to use the camera and SD card, open the rights management</string>
<string name="tip_permission_storage">No permission to use the SD card, open the rights management</string>
<string name="tip_tips">Tips</string>
<string name="tip_type_not_image">Choose not pictures</string>
```
