### ISSUE TITLE
很好用，希望在生成文件时先判断有没有旋转角度并进行旋转

### ISSUE THREAD

**Issue by xiang23** [crazycodeboy/TakePhoto#6]

**Comment by yuan9034** [comment]
对啊，我们测试机用三星手机的时候，拍照之后依附到imageview上，会出现图片旋转角度不对的问题。

**Comment by crazycodeboy** [comment]
fix in [纠正部分手机拍照照片旋转角度问题](https://github.com/crazycodeboy/TakePhoto/commit/de0cc14793acb1ebcfceb678683eaf29b1f01cf2)
