### ISSUE TITLE
获取图库中的GIF图片被压缩

### ISSUE THREAD

**Issue by skygzs** [crazycodeboy/TakePhoto#60]
图库中的GIF图片上传，被压缩了，这个框架支持 选取GIF图片然后上传么？怎么做才不会被压缩？求解

**Comment by crazycodeboy** [comment]
关掉压缩选项就可以了https://github.com/crazycodeboy/TakePhoto#api-3

**Comment by skygzs** [comment]
takePhoto.onEnableCompress(compressConfig, false);   我已经设置了关闭了，但是现在选择一个900Kb的gif图，然后在回调public void takeSuccess(TResult result) {
        File file = new File(result.getImage().getPath());
        Log.e("xx","xx:"+file.length());
