### ISSUE TITLE
无法设置图片不压缩

### ISSUE THREAD

**Issue by skygzs** [crazycodeboy/TakePhoto#62]
takePhoto.onEnableCompress(compressConfig, false); 已经设置为 false 了，现在是 2.7M的图片 变成了 900K了  然后打印了一下  ：  isCompressed:true

**Comment by crazycodeboy** [comment]
请看教程：https://github.com/crazycodeboy/TakePhoto#api-3
```
 /**
  * 启用图片压缩
  * @param config 压缩图片配置
  * @param showCompressDialog 压缩时是否显示进度对话框
  * @return
  */
 void onEnableCompress(CompressConfig config,boolean showCompressDialog);
```
上述方法为启用压缩，不调用`onEnableCompress`，就不会压缩了
