### ISSUE TITLE
图片压缩是真的垃圾

### ISSUE THREAD

**Issue by yuanmenghao** [crazycodeboy/TakePhoto#63]
压缩到100k 分辨率1920以下 图片全部压失真，而且压缩后的图片是覆盖原图的。压缩后的图片不是应该另外设置目录么，把原图覆盖了，用户手机上的照片越来越小，甚至失真，谁还用啊

**Comment by crazycodeboy** [comment]
如果想保证较高的质量可以将分辨率压缩设低一些

**Comment by yuanmenghao** [comment]
不是应该把压缩后的图片另外保存目录么

**Comment by crazycodeboy** [comment]
是的，这个在v4.0中已经带有这个功能了
