### ISSUE TITLE
进入选择图片页面或拍照页面就崩溃  华为Mate8

### ISSUE THREAD

**Issue by doubleZuo** [crazycodeboy/TakePhoto#64]
进入选择图片页面或拍照页面后，
我的应用就挂了，而且不打日志

**Comment by crazycodeboy** [comment]
按照使用教程上的做了吗？可以参考的使用方式[simple](https://github.com/crazycodeboy/TakePhoto/tree/master/simple),也可以下载demo 运行一下https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk
