### ISSUE TITLE
小米note pro选择图片有时候会崩溃

### ISSUE THREAD

**Issue by loganguo** [crazycodeboy/TakePhoto#65]
拍照或者从相册中选择都复现过崩溃。

android版本5.1.1，MIUI8.0.

华为手机GRA-UL10（P8）也有类似问题。

**Comment by crazycodeboy** [comment]
可以下载demo 运行一下看有没有类似的问题：[demo](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)

**Comment by loganguo** [comment]
怎么删掉了呢？

**Comment by crazycodeboy** [comment]
@loganguo 你在看一下

**Comment by loganguo** [comment]
我把库升级到4.0之后没有再复现出问题。

**Comment by crazycodeboy** [comment]
@loganguo 刚创建了一个TakePhoto交流群：556387607，欢迎进群讨论哦
