### ISSUE TITLE
安卓6.0拍照完了，点确认需要等很久才能跳转到裁剪的页面

### ISSUE THREAD

**Issue by zmsoft** [crazycodeboy/TakePhoto#68]
安卓6.0拍照完了，点确认需要等很久才能跳转到裁剪的页面

**Comment by crazycodeboy** [comment]
系统在启动第三方裁切工具需要些时间的（不同应用间的跳转），不同手机需要的时间不同，可以选择使用TakePhoto自带的裁切 工具裁切，这样应用内的跳转等待时间就很小了，看能否达到你的需求

**Comment by zmsoft** [comment]
我就是使用的自带的裁切工具

**Comment by zmsoft** [comment]
setWithOwnCrop

**Comment by crazycodeboy** [comment]
换一种裁切方式试一下
