### ISSUE TITLE
裁切配置比例图片没有压缩

### ISSUE THREAD

**Issue by QueenAltria** [crazycodeboy/TakePhoto#71]
裁切设置比例builder.setAspectX(width).setAspectY(height) 之后裁切出来的图片还是很大
貌似需要再设置builder.setOutputX(width).setOutputY(height) 才能对裁切图片进行压缩

**Comment by crazycodeboy** [comment]
builder.setAspectX(width).setAspectY(height) 是等比例裁切的，builder.setOutputX(width).setOutputY(height) 是裁切图片的大小
