### ISSUE TITLE
建议使用AppCompatActivity

### ISSUE THREAD

**Issue by Destiny01** [crazycodeboy/TakePhoto#82]
现在做项目Activity都用的AppCompatActivity，希望能改成AppCompatActivity

**Comment by lxykad** [comment]
是啊，本来继承AppCompatActivity 的，现在继承activity 不行。

**Comment by crazycodeboy** [comment]
TakePhoto支持两种使用方式，没有继承Activity的可以通过[组装的形式](https://github.com/crazycodeboy/TakePhoto#使用takephoto有以下两种方式)使用TakePhoto
