### ISSUE TITLE
使用多图选择并裁剪时,获取到的图片有几率是重复的

### ISSUE THREAD

**Issue by leijiaxq** [crazycodeboy/TakePhoto#85]

**Comment by crazycodeboy** [comment]
没明白你的意思，建议你下载[Demo](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)运行一下

**Comment by leijiaxq** [comment]
就是同时选择多张图片,依次裁剪,在方法takeSuccess(TResult result) 中调用result.getImages()获取到的ArrayList<TImage> 集合,遍历,通过 getPath得到的图片地址有时候是相同的
