### ISSUE TITLE
图片会裁剪两次

### ISSUE THREAD

**Issue by lxykad** [crazycodeboy/TakePhoto#86]
TakePhoto.onPickFromGalleryWithCrop 调用此方法，图片会裁剪两次，请问什么情况？

**Comment by crazycodeboy** [comment]
你有选择两张图片吗？多张图片会每张图片都裁切一次的，另外你可以下载Demo运行一下：[simple-debug.apk](https://github.com/crazycodeboy/TakePhoto/blob/master/simple/simple-debug.apk)
