### ISSUE TITLE
拍照压缩之后图片还很大，相册选取图片没有压缩处理

### ISSUE THREAD

**Issue by Yanqilong** [crazycodeboy/TakePhoto#91]
第一：不管用自带压缩还是鲁班压缩，用三星拍照返回，压缩后的结果有四点几兆，和没压缩一样，以前的版本不会。
第二：相册选取图片没有压缩处理

**Comment by crazycodeboy** [comment]
是不知压缩配置的问题，这里有个4.0版本的[demo](https://github.com/crazycodeboy/TakePhoto/tree/master/simple)，你参考一下

**Comment by Yanqilong** [comment]
我是下载源码跑起来的demo，没改东西

**Comment by crazycodeboy** [comment]
三星什么型号的手机？

**Comment by crazycodeboy** [comment]
@Yanqilong 刚创建了一个TakePhoto交流群：556387607，进群讨论吧
