### ISSUE TITLE
LubanOptions压缩使用了RxJava，建议在文档添加RxJava的混淆说明

### ISSUE THREAD

**Issue by TravellingBee** [crazycodeboy/TakePhoto#97]
我在使用时，使用LubanOptions压缩，混淆后发现会崩溃。经过一番检查，才发现是因为Luban压缩中使用了RxJava。需要在proguard文件中添加RxJava的配置。建议楼主添加到说明文档中。
附RxJava  proguard配置
`-dontwarn sun.misc.**
-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
   long producerIndex;
   long consumerIndex;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode producerNode;
}
-keepclassmembers class rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef {
    rx.internal.util.atomic.LinkedQueueNode consumerNode;
}`

**Comment by crazycodeboy** [comment]
#102 ，thanks
