### ISSUE TITLE
使用Luban压缩时，选取多张图片，返回的图片经常出现重复。

### ISSUE THREAD

**Issue by TravellingBee** [crazycodeboy/TakePhoto#99]
使用LubanOptions压缩，选择图片a、b、c、d四张图，返回时经常重复（比如a、a、b、c)

另外，使用自带的压缩，不管图片是否超出给定的大小限制，都会压缩生成新文件。建设可以优化下，未超出限制就返回原文件就行了。

**Comment by crazycodeboy** [comment]
@TravellingBee 为了不覆盖原图，压缩时统一产生新路径的，同时也返回了原路径，你可以根据需要进行处理。LubanOptions压缩重复的问题后期会检测修复
